// This file will be dynamically imported to avoid SSR issues
// @ts-nocheck
import type { TDocumentDefinitions } from 'pdfmake/interfaces';

export class MarkdownPDFGenerator {
  static async generateFromMarkdown(markdown: string, title?: string): Promise<Blob> {
    // Dynamically import dependencies
    const [
      { default: pdfMake },
      { default: pdfFonts },
      { default: MarkdownIt }
    ] = await Promise.all([
      import('pdfmake/build/pdfmake'),
      import('pdfmake/build/vfs_fonts'),
      import('markdown-it')
    ]);

    // Initialize pdfMake with fonts
    if (pdfFonts && pdfFonts.pdfMake && pdfFonts.pdfMake.vfs) {
      pdfMake.vfs = pdfFonts.pdfMake.vfs;
    } else if (pdfFonts && (pdfFonts as any).vfs) {
      pdfMake.vfs = (pdfFonts as any).vfs;
    } else {
      // Fallback: set vfs directly from pdfFonts
      pdfMake.vfs = pdfFonts;
    }

    // Define fonts - pdfmake comes with Roboto by default
    pdfMake.fonts = {
      Roboto: {
        normal: 'Roboto-Regular.ttf',
        bold: 'Roboto-Medium.ttf',
        italics: 'Roboto-Italic.ttf',
        bolditalics: 'Roboto-MediumItalic.ttf'
      }
    };

    // Parse markdown
    const md = new MarkdownIt({
      html: true,
      linkify: true,
      typographer: true,
    });

    const tokens = md.parse(markdown, {});
    
    // Convert markdown tokens to pdfmake content
    const content: any[] = [];
    
    // Add title if provided
    if (title) {
      content.push({
        text: title,
        fontSize: 24,
        bold: true,
        alignment: 'center',
        margin: [0, 0, 0, 10]
      });
      content.push({
        text: 'Generated by AI Report Agent',
        fontSize: 12,
        italics: true,
        alignment: 'center',
        color: '#666',
        margin: [0, 0, 0, 30]
      });
    }

    // Process tokens
    let currentList: any[] | null = null;
    let listType: 'ul' | 'ol' | null = null;
    let listCounter = 1;
    let inTable = false;
    let tableRows: any[] = [];
    let currentRow: any[] = [];

    for (let i = 0; i < tokens.length; i++) {
      const token = tokens[i];

      switch (token.type) {
        case 'heading_open':
          const nextToken = tokens[i + 1];
          if (nextToken && nextToken.type === 'inline') {
            const level = parseInt(token.tag.substring(1));
            content.push({
              text: nextToken.content,
              fontSize: 26 - (level * 2),
              bold: true,
              margin: [0, 15, 0, 10]
            });
            i++; // Skip inline token
          }
          break;

        case 'paragraph_open':
          const paraToken = tokens[i + 1];
          if (paraToken && paraToken.type === 'inline' && !currentList && !inTable) {
            const formattedText = this.formatInlineContent(paraToken.content);
            content.push({
              text: formattedText,
              margin: [0, 5, 0, 5],
              alignment: 'justify'
            });
            i++; // Skip inline token
          }
          break;

        case 'code_block':
        case 'fence':
          // Check if this is a mermaid diagram
          if (token.info === 'mermaid') {
            // Extract diagram type and title from the content
            const typeMatch = token.content.match(/^(graph|sequenceDiagram|classDiagram|stateDiagram|erDiagram|gantt|pie|flowchart|gitGraph|journey|C4Context|mindmap|timeline|quadrantChart|requirementDiagram|sankey-beta|xychart-beta|block-beta|zenuml)/m);
            const titleMatch = token.content.match(/title\s+(.+)/);
            
            const diagramType = typeMatch ? typeMatch[1] : 'Diagram';
            const diagramTitle = titleMatch ? titleMatch[1] : null;
            
            // Add a styled placeholder for the Mermaid diagram
            content.push({
              stack: [
                {
                  text: `[${diagramType.toUpperCase()} DIAGRAM]`,
                  fontSize: 12,
                  bold: true,
                  alignment: 'center',
                  color: '#333',
                  margin: [0, 10, 0, 5]
                },
                {
                  text: diagramTitle || 'Interactive diagram available in web view',
                  fontSize: 10,
                  italics: true,
                  alignment: 'center',
                  color: '#666',
                  margin: [0, 0, 0, 5]
                },
                {
                  canvas: [{
                    type: 'rect',
                    x: 50,
                    y: 0,
                    w: 415,
                    h: 100,
                    r: 5,
                    lineWidth: 1,
                    lineColor: '#ccc',
                    color: '#f9f9f9'
                  }],
                  margin: [0, 5, 0, 5]
                },
                {
                  text: 'Note: Mermaid diagrams are best viewed in the web interface.\nThis PDF shows a placeholder for the interactive diagram.',
                  fontSize: 9,
                  alignment: 'center',
                  color: '#888',
                  margin: [40, -95, 40, 0]
                }
              ],
              margin: [0, 10, 0, 10]
            });
          } else {
            // Regular code block
            content.push({
              text: token.content,
              fontSize: 10,
              background: '#f5f5f5',
              margin: [10, 5, 10, 5],
              preserveLeadingSpaces: true,
              font: 'Roboto', // Use default font
              bold: false,
              italics: false
            });
          }
          break;

        case 'bullet_list_open':
          currentList = [];
          listType = 'ul';
          break;

        case 'ordered_list_open':
          currentList = [];
          listType = 'ol';
          listCounter = 1;
          break;

        case 'bullet_list_close':
        case 'ordered_list_close':
          if (currentList && listType) {
            content.push({
              [listType]: currentList,
              margin: [20, 5, 0, 10]
            });
            currentList = null;
            listType = null;
          }
          break;

        case 'list_item_open':
          const itemToken = tokens[i + 2]; // Skip paragraph_open
          if (itemToken && itemToken.type === 'inline' && currentList) {
            const text = this.formatInlineContent(itemToken.content);
            if (listType === 'ol') {
              currentList.push({ text, listType: 'decimal' });
            } else {
              currentList.push(text);
            }
          }
          break;

        case 'blockquote_open':
          const quoteContent: string[] = [];
          let j = i + 1;
          while (j < tokens.length && tokens[j].type !== 'blockquote_close') {
            if (tokens[j].type === 'inline') {
              quoteContent.push(tokens[j].content);
            }
            j++;
          }
          content.push({
            stack: [{
              text: quoteContent.join(' '),
              italics: true,
              color: '#666',
              margin: [20, 5, 0, 5]
            }],
            margin: [0, 5, 0, 10]
          });
          i = j; // Skip to blockquote_close
          break;

        case 'hr':
          content.push({
            canvas: [{
              type: 'line',
              x1: 0,
              y1: 0,
              x2: 515,
              y2: 0,
              lineWidth: 0.5,
              lineColor: '#ccc'
            }],
            margin: [0, 10, 0, 10]
          });
          break;

        case 'table_open':
          inTable = true;
          tableRows = [];
          break;

        case 'table_close':
          if (tableRows.length > 0) {
            // Determine column widths
            const columnCount = tableRows[0].length;
            const widths = new Array(columnCount).fill('*');
            
            content.push({
              table: {
                headerRows: 1,
                widths: widths,
                body: tableRows
              },
              layout: 'lightHorizontalLines',
              margin: [0, 10, 0, 10]
            });
          }
          inTable = false;
          tableRows = [];
          break;

        case 'thead_open':
        case 'tbody_open':
          // No action needed
          break;

        case 'tr_open':
          currentRow = [];
          break;

        case 'tr_close':
          if (currentRow.length > 0) {
            tableRows.push(currentRow);
          }
          break;

        case 'th_open':
        case 'td_open':
          const cellToken = tokens[i + 1];
          if (cellToken && cellToken.type === 'inline') {
            const isHeader = token.type === 'th_open';
            currentRow.push({
              text: cellToken.content,
              bold: isHeader,
              fillColor: isHeader ? '#f5f5f5' : null
            });
          }
          break;
      }
    }

    // Create PDF document definition
    const docDefinition: TDocumentDefinitions = {
      content: content,
      defaultStyle: {
        fontSize: 12,
        lineHeight: 1.5
      },
      styles: {
        header: {
          fontSize: 22,
          bold: true
        }
      },
      pageMargins: [40, 60, 40, 60]
    };

    // Generate PDF and return blob
    return new Promise((resolve, reject) => {
      try {
        const pdfDoc = pdfMake.createPdf(docDefinition);
        pdfDoc.getBlob((blob: Blob) => {
          resolve(blob);
        });
      } catch (error) {
        reject(error);
      }
    });
  }

  private static formatInlineContent(content: string): any {
    // Handle bold, italic, and inline code
    const parts: any[] = [];
    let remaining = content;
    
    // Simple regex-based parsing for inline formatting
    const patterns = [
      { regex: /\*\*(.+?)\*\*/g, style: { bold: true } },
      { regex: /\*(.+?)\*/g, style: { italics: true } },
      { regex: /`(.+?)`/g, style: { fontSize: 10, background: '#f0f0f0' } }
    ];

    // For now, return simple text
    // TODO: Implement proper inline formatting
    return content
      .replace(/\*\*(.+?)\*\*/g, '$1')
      .replace(/\*(.+?)\*/g, '$1')
      .replace(/`(.+?)`/g, '$1')
      .replace(/\[(.+?)\]\((.+?)\)/g, '$1');
  }

  static estimatePages(markdown: string): number {
    const lines = markdown.split('\n').length;
    const words = markdown.split(/\s+/).length;
    return Math.max(Math.ceil(lines / 30), Math.ceil(words / 500));
  }
}